### ISSUE TITLE
carousel images

### ISSUE THREAD

**Issue by hughmp** [hughmp/thementawaiislands#21]

**Comment by hughmp** [comment]
I suggest max of three types - 
1. portrait mobile friendly mid-res
2. landscape high-res
3. landscape low-res

**Comment by oliquick** [comment]
Ok - i'll try to work on some templates for this

**Comment by oliquick** [comment]
If you can get me some dimentions to work with then it will be easy. I'll research target resolutions for mobile devices. 
1 question - do we duplicate each image to meet each resolution requirement and then upload each one? The the browser then retrieve the appropriate image depending on the device?
