### ISSUE TITLE
Landing Page Suggestion...

### ISSUE THREAD

**Issue by oliquick** [hughmp/thementawaiislands#25]
www.greatnorthco.com 

This is a quality and visually impressive option. Navigation subtly within the image with carouselling content. 

Options: 

i) forced to click on the logo or nav to enter the site. 
ii) option to then scroll down to other 'Home page' content as described in the Contents Document

The later would require some smart image management to not present the content below the full-screen image without the user intending to discover it by scrolling down. I think the ii) option would be easier? 

The current carousel would still remain active but within the second layer of the site when you click on the image or logo

**Comment by hughmp** [comment]
So what I'm imagining is something like this:

https://www.blockchain.com/

The menu system is overlaid on the full-screen image which also acts as the landing page. When you scroll over the first page, the header menu changes to a translucent white. If we're sticking with the original logo, perhaps the header should be dark like before.

Do you want that main image to change automatically (carousel style), or should we just change it on a rotational manual basis from the back-end and leave carousels for other sections?

**Comment by hughmp** [comment]
think we've decided on this. closing.
